config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  #route to access the report of tasks done. 
  get 'report', to: 'report#index'
  get 'mytasks', to: 'tasks#mytasks'

  resources :tasks 

  resources :profiles, only: %i[show new create update edit] do
    get 'private_page', on: :member
    post 'change_privacy', on: :member
    resources :comments, only: %i[index]
  end

  resources :pluses, only: %i[create destroy]
  resources :minuses, only: %i[create destroy]
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :nickname, uniqueness: {message: 'Nickname Taken! Chose Another one'}
  validates :nickname, length: {minimum: 4, message: 'Nickname too short, Minimum of 4 characters'}
  validates :nickname, length: {maximum: 20, message: 'Nickname too long, Maximum of 20 characters'}
  validates :bio, presence: {message: 'Bio cannot be blank'}
  validates :bio, length: {maximum: 500, message: 'Bio Max Length is 500 characters'}
  
  belongs_to :user
  has_one_attached :avatar

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :public?, except: %i[private_page]
 #create body of the method -> show
  def show 
    @profile = Profile.find(params[:id])
      respond_to do | format |
        format.html
      end

  end

  def new
    @profile = Profile.new
  end

  def create 
    @profile = Profile.create(profile_params)
    @profile.user = current_user
    current_user.profile_id = @profile.id
    if @profile.save
      flash[:notice] = 'Profile Created!'
      redirect_to @profile
    else
      render :new
    end
  end

  def edit 
  end
#fix update profile
  def update
    if @profile.update(profile_params)
      flash[:notice] = 'Profile Updated!'
      redirect_to @profile
    else
      render :edit
    end 
  end
#fix change provacy. was not receiving the ID.
  def change_privacy
    @profile = Profile.find(params[:id])
    @profile.update(privacy_params)
    redirect_to @profile
  end

  def private_page 
  end

  private 
#define params of Profile
  def profile_params
    params.require(:profile).permit(:nickname, :bio, :share)
  end 

  def privacy_params
    params.require(:profile).permit(:share)
  end

  def find_profile
    @profile = Profile.find(params[:id])
  end
#alther 
  def public?
    if (current_user.profile == @profile)
      if @profile.share
        redirect_to private_page_profile_path(@profile)
      end
    end
  end

end
  

app/views/profiles/edit.html.erb
<% @profile.errors.full_messages.each do |error| %> 
  <p><%= error %> </p> 
<% end %>

  <p> Edit <%= @profile.nickname %> Profile </p>
  <%= form_for @profile do |f| %> 

      <%= f.hidden_field :user_id, value: params[:id]%>

      <div>
        <%= f.label :bio, 'Your Bio:'%>
        <%= f.text_area :bio, class: 'form-control mb-2', rows: '4'%>
      </div>

        <br>

      <div>
        <%= f.label :avatar, 'Your Profile Picture' %>
        <%= f.file_field :avatar %>
      </div>

        <br>

      <div>
        <%= f.submit class: 'btn btn-primary col-4'%>
        <%= link_to 'Go Back', :back, class: 'btn btn-secondary col-4' %>
      </div>
  <% end %>

app/views/profiles/new.html.erb
<!-- Error Messages -->
<% @profile.errors.full_messages.each do |error| %> 
  <p><%= error %> </p> 
<% end %> 

<!-- Form -->
<div class='form-group align-item-center container border' >
  <%= form_for @profile do |f| %>
    <div class='row'>  
      <p class='col-4'></p>
      <div class='col-4 text-center' >
        <%= f.label :nickname, 'Nickname:' %>
        <%= f.text_field :nickname, class: 'form-control mb-2', placeholder: 'Your Nickname'%>
      </div>
    </div>
    <br> 
      
    <div class='row'>
      <p class='col-4'></p> 
      <div class='col-4' align='center'>
        <%= f.label :bio, 'You Bio'%>
        <%= f.text_area :bio, class: 'form-control mb-2', rows: '4'%>
      </div> 
    </div>

    <br>

    <div class='row'>
      <p class='col-4'></p> 
      <div class='col-4' align='center'>
        <%= f.label :avatar, 'Your Profile Picture' %>
        <%= f.file_field :avatar %>
      </div>
    </div>

    <br>

    <div class='row'>
      <p class='col-4'></p> 
      <div class='col-4' align='center'> 
        <%= f.hidden_field :user_id, value: params[:id]%>
        <%= f.submit class: 'btn btn-primary col-4'%>
        <%= link_to 'Go Back', :back, class: 'btn btn-secondary col-4' %>
      </div>
    </div>

  <% end %>
</div>

app/views/profiles/private_page.html.erb
<div class='text-center'>
  <h3 class=''>@<%= "#{@profile.nickname}" %> Profile is Private </h3> 
  <br>
  <br>
  <%= link_to 'Go Back', :back, class: 'btn btn-secondary' %>
</div>

app/views/profiles/show.html.erb
<div class='container border'>
  
  <div class='row'>
    <% if @profile == current_user.profile %>
      <h1 class='col', align='center'> Welcome, <%= @profile.nickname %>!</h1> 
    <% else %>
      <h1 class='col', align='center'> Welcome to <%= @profile.nickname %>'s Profile!</h1> 
    <% end %>
  </div>
  <div class='row'> 
    <p class='col-5'></p>
    <small class='col-4'> This Profile is <%= @profile.share ? 'Public' : 'Private' %></small>
  </div>

  <br> 

  <br>

  <div class='row'> 
    <p class='col-2'><strong>Profile Picture</strong>:</p> 
    <% if @profile.avatar.attached? %>
      <%= image_tag(@profile.avatar, class:'img-fluid col-2 border') %> 
    <% else %>
      <p class='col-4'>Empty</p>
    <% end %>

    <p class='col-4 text-center text-wrap text-break'  align='center' style='white-space' >
      <strong>Bio</strong>:
      <br>
      <%= @profile.bio %>
    </p>
  </div>

  <br> 

  <div class='row'>
    <p class='col-4'></p>
      <% if current_user == @profile.user %>
        <%= form_for(@profile, url: change_privacy_profile_path, method: :post, class: 'form-inline') do |f| %> 
        <div class='form-group'>
          <strong class='text-center'><%= f.label :share, 'Change Privacy:' %></strong>
          <%= f.select(:share, [['Private', false], ['Public', true]]) %> 
          <%= f.hidden_field :profile_id, value: params[:id] %> 
          <%= f.submit 'Change Setting' %>
        </div>
        <% end %>
      <% end %>
  </div>

  <br>

    <div class='row'>
      <p class='col-4'></p>
      <% if current_user == @profile.user %> 
        <%= link_to 'Edit Info', edit_profile_path(@profile), class: 'text-white btn btn-primary col-2'%>
      <% end %>
      <%= link_to 'Go Back', :back, class: 'btn btn-secondary col-2' %>
    </div>
    <br>
    <br>
    <br> 
</div>