config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  #route to access the report of tasks done. 
  get 'report', to: 'report#index'
  get 'mytasks', to: 'tasks#mytasks'

  resources :tasks 

  resources :profiles, only: %i[show new create update edit] do
    get 'private_page', on: :member
    post 'change_privacy', on: :member
    resources :comments, only: %i[index]
  end

  resources :pluses, only: %i[create destroy]
  resources :minuses, only: %i[create destroy]
end

app/models/task.rb
class Task < ApplicationRecord
  enum priority: {low: 0, medium: 10, high: 20}
  enum status: {incomplete: 0, complete: 10}

  validates :title, length: {minimum: 4}
  validates :title, length: {maximum: 20}
  validates :description, presence: true 
  validates :description, length: {maximum: 280} 

  belongs_to :user
  has_many :comments

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create destroy search]
  before_action :user_profile?
  before_action :find_task, only: %i[edit update show confirm_delete destroy delete_comment]
  skip_before_action :verify_authenticity_token, only: %i[search]
    
  def index
    @tasks = Task.all
  end
  def mytasks
    @tasks = current_user.tasks.all
  end

 

  def show 
    @task = Task.find(params[:id])
      respond_to do | format |
        format.html
      end
  end

  def find_task
    @task = Task.find(params[:id])
  end
  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    @task.user = current_user
    if @task.save
      flash[:notice] = 'Task Created!'
      redirect_to @task
    else
      render :new
    end
  end

  def edit
    
  end


  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html
    end
  end

  def complete
  end

  def incomplete
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :status, :priority, :user_id)
  end  

  def comment_params
    params.require(:comment).permit(:body)
  end 

  def sanitize_sql_like(string, escape_character = "\\")
    pattern = Regexp.union(escape_character, "%", "_")
    string.gsub(pattern) { |x| [escape_character, x].join }
  end
end

app/views/tasks/_form.html.erb
<div class='form-group align-item-center container border' >
  <%= form_for @task do |f| %>

    <div class='row'>  
      <p class='col-4'></p>
        <%= f.label 'User:' %>
        <br>
      <div class='col-4 text-center' >
        <%= current_user.email%>
      </div>
      <p class='col-4'></p>
        <%= f.label 'Profile:' %>
        <br>
      <div class='col-4 text-center' >
        <%= current_user.profile.nickname%>
      </div>
    </div>


    <br> 

    <div class='row'>  
      <p class='col-4'></p>
      <div class='col-4 text-center' >
        <%= f.label :title, 'Title:' %>
        <%= f.text_field :title, class: 'form-control mb-2', placeholder: 'Task Tittle'%>
      </div>
    </div>
    <br> 
      
    <div class='row'>
      <p class='col-4'></p> 
      <div class='col-4' align='center'>
        <%= f.label :description, 'Task description'%>
        <%= f.text_area :description, class: 'form-control mb-2', rows: '4'%>
      </div> 
    </div>

    <br>
    <div class='row'>  
      <p class='col-4'></p>
      <div class='col-4 text-center' >
        <%= f.label :status, 'Status:' %>
        <%= f.select :status, ["incomplete", "complete"], class: 'form-control mb-2', placeholder: 'Task Status'%>
      </div>
    </div>
    <br>
        <div class='row'>  
      <p class='col-4'></p>
      <div class='col-4 text-center' >
        <%= f.label :priority, 'Priority:' %>
        <%= f.select :priority, ["low", "medium", "high"], class: 'form-control mb-2', placeholder: 'Task Priority'%>
      </div>
    </div>
    

    <br>

    <div class='row'>
      <p class='col-4'></p> 
      <div class='col-4' align='center'> 
        <%= f.hidden_field :task_id, value: params[:id]%>
        <%= f.submit class: 'btn btn-primary col-4'%>
        <%= link_to 'Go Back', :back, class: 'btn btn-secondary col-4' %>
      </div>
    </div>

  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>
<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/mytasks.html.erb
<br>
<h1>All my tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Priority</th>
      <th>Status</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.priority %></td>
        <td><%= task.status %></td>
        <td><%= task.user.email %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<h1>Listing Task <%= @task.id%></h1>
<div class='container border'>
    <% if @task == current_user.tasks.find(@task.id) %>
      <h1> Title</h5> 
        <%= @task.title %>!</h1>
      <br>
      <h5> Description</h5>
        <%= @task.description %></h5>
      <br>
      <h5> Status</h5> 
        <%= @task.status %></h5>
      <br>
      <h5>Share</h5> 
      <%= @task.share %></h5>
      <br>
    <% end %>
  </div>