config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  #route to access the report of tasks done. 
  get 'report', to: 'report#index'
  get 'mytasks', to: 'tasks#mytasks'

  resources :tasks 

  resources :profiles, only: %i[show new create update edit] do
    get 'private_page', on: :member
    post 'change_privacy', on: :member
    resources :comments, only: %i[index]
  end

  resources :pluses, only: %i[create destroy]
  resources :minuses, only: %i[create destroy]
end

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">

    <!--Navbrand -->
    <%= button_to root_path, method: :get, class: 'nav-brand btn btn-outline-primary' do %>
      <i class="fa fa-home" aria-hidden="true"></i>
    <% end %> 

    <!--Navbar for loged in user -->
    <% if (user_signed_in?)%> 
      <!-- Dropdown -->
      <div class="btn-group ml-3"> 
        <button type="button" class="btn btn-outline-primary"><i class='fa fa-tasks'></i> 
          <%= link_to 'Your Tasks', '/mytasks'%>
        </button> 
        <button type="button" class="btn btn-outline-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <div class="dropdown-menu">
          <%= link_to ' Task Board', tasks_path, class: 'fa fa-laptop dropdown-item'%>
        </div>
      </div> 
      <!-- create task -->
      <%= link_to ' Create a Task', new_task_path, class: 'fa fa-cart-plus btn btn-outline-success ml-3'  %>
      <%= link_to ' Completed Tasks', "/report" , class: 'fa fa-check btn btn-outline-warning ml-3'%>

      <!-- Search -->
      <div class='ml-auto mr-auto'>
      </div> 
      <!-- Profile Settings -->
      <!-- Dropdown -->
      <div class="btn-group">
        <button type="button" class="btn btn-outline-primary"><i class='fa fa-user-circle'></i>  Account Settings</button> 
        <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </button>
        <div class="dropdown-menu"> 
          <% if current_user.profile && current_user.profile.id %>
            <%= link_to '  My Profile', profile_path(current_user.profile), class: 'fa fa-cogs dropdown-item'%> 
            <%= link_to '  My Comments', profile_comments_path(current_user.profile), class: 'fa fa-comments dropdown-item' %>
      <% end %>
        </div>
      </div> 

      <!-- Log Out -->
      <%= link_to ' Log Out', destroy_user_session_path, method: :delete, class: 'fa fa-power-off btn btn-outline-danger ml-auto'%> 

    <!-- Navbar for Visitor -->
    <% else %> 
     <%=link_to 'Log In', new_user_session_path, class: 'btn btn-outline-primary ml-auto' %>
     <%=link_to 'Create Account', new_user_registration_path, class: 'btn btn-outline-success ml-3' %>
    <% end %>
    </nav>